### ISSUE TITLE
Просьба по модификации

### ISSUE THREAD

**Issue by shinzzza** [Nzt2/massann_dahua#1]
Сейчас у меня программа авторизует несколько ип и потом ошибка. Может не хватает выделяемой памяти? Работает без сбоев только с маленьким диапазоном ипов.

**Comment by iggypoper** [comment]
Аналогичная проблема и у меня. massann_dahua стабильно работает, если в файле "scan.txt" не более 50 IP-адресов. В противном случае, после скана и авторизации 10-15 айпишников программа вылетает с ошибкой AppCrash python.exe. Установлен python_3.4.3. Проверял на машинах с Windows 8.1 x64 и Windows 7 x64. Памяти на обеих хватает.
 Пробовал полностью отключать DEP (предотвращение выполнения данных на  Windows) - проблему это не устранило.
Большая просьба поправить, так как сканить по 50 айпишников очень муторно :)
Спасибо.

**Comment by shinzzza** [comment]
(iggypoper -Памяти на обеих хватает.) Имеется ввиду количество выделяемой оперативной памяти **Питону**. По умолчанию это значение достигает 4 Гб. Я лично massann_dahua переделал под себя, но еще не тестил.

**Comment by iggypoper** [comment]
Не подскажете, как в Винде уменьшить количество памяти, выделяемой Питону? Или, может, поделитесь переделанной версией? Переделывали ведь с целью улучшения стабильности?

**Comment by shinzzza** [comment]
Я в стабильности не шарю, схватил только азы Пайтона.  Просто massсan откинул и чуть допилил. Отработаю ранее листы Украины,  и опробую.. может еще "аут" подкручу. Не хочется Даху доводить до учести Хики.

**Comment by Nzt2** [comment]
Добрый день, проверял на больших, диапазонах все работало у меня,,не более 50 адресов в масскане или масскан проходит нормально? Параметры машин ваших озу итд, и лог консоли если можно полный.

**Comment by shinzzza** [comment]
Лог консоли как снять? На Linux так и не пашет???
Имя ОС	Майкрософт Windows 10 Корпоративная 2015 с долгосрочным обслуживанием
Версия	10.0.10240 Сборка 10240
Изготовитель	ASUS
Тип	Компьютер на базе x64
Процессор	Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz, 3401 МГц, ядер: 4, логических процессоров: 8
Установленная оперативная память (RAM)	8,00 ГБ
Полный объем физической памяти	7,91 ГБ
Доступно физической памяти	5,54 ГБ

**Comment by Nzt2** [comment]
Скопируй и выложи сюда, на линукс нет, не было времени заниматься этой программной, да и не актуальна уже дахуя теперь на новых регистраторах сразу просит менять пароль.
Вот мой лог запушенный.
ann_dahua\masscan_dahua.py -f scan.txt -t 25
[*] Starting scan in masscan

Starting masscan 1.0.3 (http://bit.ly/14GZzcT) at 2017-07-02 20:15:28 GMT (compi
led for www.Proxy-Base.Org members)
 -- forced options: -sS -Pn -n --randomize-hosts -v --send-eth
Initiating SYN Stealth Scan
Scanning 40976 hosts [1 port/host]
rate:  0.02-kpps, 11.71% done,   0:27:36 remaining, found=7
Тут явно видно что больше 50 адресов в файле  скан.
Закончит сканирование выложу полный лог.
Диапазоны просто копирую с сайта https://4it.me

**Comment by shinzzza** [comment]
Масскан отрабатывает нормально. Когда авторизуется тогда вылетает.
Я не силен в пайтоне, скажи вот тут
for string in file.readlines():
        line = string.split(' ')
        if not (string.startswith('#')):
if Auth(line[3]):
весь файл в памяти или построчно обрабатывается

**Comment by Nzt2** [comment]
Мне нужен лог ошибок, что-бы понять что у вас не так.
если вы брали сдк с репозитория то будет работать только с 32х разрядным питоном, проверьте какой у вас. Для 64 бит нужно другие длл. Вот ссылка на питон с ним должно работать, удалите только предыдущий. https://www.python.org/ftp/python/3.6.1/python-3.6.1-webinstall.exe

**Comment by shinzzza** [comment]
У меня Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 07:18:10) [MSC v.1900 32 bit (Intel)] on win32
Можно попробовать поставить 64ый и DLL тоже 64! Я пробовал 64 питон с 32ной DLL вообще не авторизуется и вроде не запускался писал что-то не является 32 приложением 
Сейчас таких Host 111.111.111.111 found + из 500 ипов до конца обрабатывает.

**Comment by Nzt2** [comment]
весь файл считывает построчно и возвращает список. Ну с объемом 8 гиг должно хватать.
Если можете залейте ваш большой файл с айпишниками, постараюсь исправить,
Можете сами fileObject.readlines( sizehint ); Если необязательный sizehint аргумент присутствует, вместо чтения до EOF, целые линии на общую сумму около sizehint байт (possibly after rounding up to an internal buffer size) считываются. у меня больше 80мб не взяло на проверки 55 хостов

**Comment by Nzt2** [comment]
Ну если все ок то тему можно закрывать?

**Comment by shinzzza** [comment]
Прикрутить просмотр сколько сколько обработано или % осталось можно???

**Comment by Nzt2** [comment]
да можно на досуге займусь, А тему закрываю.
