### ISSUE TITLE
вопрос по  DLL

### ISSUE THREAD

**Issue by shinzzza** [Nzt2/massann_dahua#2]
Заинтересовал вылет "скрипта" при большом диапазоне ипов при авторизации. 
Заметил что после авторизации поддерживается соединение с хостом до конца отработки скрипта. Вылет происходит когда количество TCP-подключений переваливает за 250.  
Думаю в DLL ограничение на 255 соединений, ведь есть ограничении импортируемого листа в Smart_pss.

**Comment by Nzt2** [comment]
ограничение импорта реализовано, оно просто создает 2й файл, смотрите строку в коде 75.
А по поводу закрытия соединения, имеет право на жизнь. В скором времени исправлю

**Comment by Nzt2** [comment]
И выкладывайте лог ошибок, понять что конкретно не так без лога я не могу!
Добавил отключение, тестируйте.

**Comment by shinzzza** [comment]
Как хорошо когда знаешь языки! Теперь все идеально! Спасибо!!!

**Comment by Nzt2** [comment]
Ок, закрываю тогда. Если что пишите.
